-- ALTER SYSTEM SET SEC_CASE_SENSITIVE_LOGON = TRUE;

SHUTDOWN IMMEDIATE ;
STARTUP RESTRICT;
ALTER DATABASE CHARACTER SET INTERNAL_USE WEMSWIN1252;
SHUTDOWN IMMEDIATE;
STARTUP OPEN;

-- CREAR UN DATATABLE PARA EL USUARIO
CREATE BIGFILE TABLESPACE MIUMGTS DATAFILE '/u01/oradata/ORCL/MiUMG_TS_01.dbf'
    SIZE 10M
    AUTOEXTEND ON
    MAXSIZE 1G
    BLOCKSIZE 8K
    EXTENT MANAGEMENT LOCAL
    UNIFORM
    SIZE 512K
    ONLINE;

-- ALTERAR LA SESIÓN
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- CREAR USUARIO MIUMG
CREATE USER miumg
    IDENTIFIED BY miumg
    DEFAULT TABLESPACE MIUMGTS
    TEMPORARY TABLESPACE TEMP
    QUOTA 1G ON MIUMGTS
    ACCOUNT UNLOCK;

-- OTORGAR PERMISOS DE CONECCIÓN Y CREACIÓN DE OBJETOS
GRANT RESOURCE TO MIUMG;
GRANT CONNECT TO MIUMG;
GRANT CREATE VIEW TO MIUMG;